name: Deploy

on:
  push:
    branches:
      - main


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14 # Specify the version of Node.js you want to use


      - name: Install all dependencies
        run: |
          yarn install --frozen-lockfile 

      - name: Build the source code
        run: |
          yarn build

      - name: Deploy to Cloudflare Pages
        run: |
          npx wrangler deploy


        env:
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}