name: Deploy

on:
  push:
    branches:
      - main


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18 # Specify the version of Node.js you want to use


      - name: Install all dependencies
        run: |
          yarn install --frozen-lockfile 

      - name: Build the source code
        run: |
          yarn build

      - name: Deploy to Cloudflare Pages
        run: |
            npx wrangler pages  deploy ./dist --project-name=cmink-website


        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID}}