name: Deploy

on:
  push:
    branches:
      - main


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Bun
        run: |
          curl -fsSL https://bun.sh/install | bash 

      - name: Install all dependencies
        run: |
          ~/.bun/bin/bun install

      - name: Build the source code
        run: |
          ~/.bun/bin/bun run build

      - name: Deploy to Cloudflare Pages
        run: |
            ~/.bun/bin/bunx wrangler pages  deploy ./dist --project-name=cmink-website


        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID}}